export default {
  bug: { backgroundColor: "#A6B91A", text: "black" },
  dark: { backgroundColor: "#705746", text: "white" },
  dragon: { backgroundColor: "#6F35FC", text: "white" },
  electric: { backgroundColor: "#F7D02C", text: "black" },
  fairy: { backgroundColor: "#D685AD", text: "black" },
  fighting: { backgroundColor: "#C22E28", text: "white" },
  fire: { backgroundColor: "#EE8130", text: "white" },
  flying: { backgroundColor: "#A98FF3", text: "black" },
  ghost: { backgroundColor: "#735797", text: "white" },
  grass: { backgroundColor: "#7AC74C", text: "black" },
  ground: { backgroundColor: "#E2BF65", text: "black" },
  ice: { backgroundColor: "#96D9D6", text: "black" },
  normal: { backgroundColor: "#A8A77A", text: "black" },
  poison: { backgroundColor: "#A33EA1", text: "white" },
  psychic: { backgroundColor: "#F95587", text: "white" },
  rock: { backgroundColor: "#B6A136", text: "black" },
  steel: { backgroundColor: "#B7B7CE", text: "black" },
  water: { backgroundColor: "#6390F0", text: "white" },
};
